### ISSUE TITLE
[tx:WebServer:DiagnosticsFuncs] Error getting processes tree usage data.

### ISSUE THREAD

**Issue by Poseidon281** [Luxxy-GF/pterodactyl-fivem#2]
I get this error with TX when using: Skull x Luxxy FiveM Egg 2.0

![image](https://github.com/Luxxy-GF/pterodactyl-fivem/assets/62171904/4285d565-4520-436b-bc4a-ee39b25c0ef5)

**Comment by Luxxy-GF** [comment]
Hello 
Sorry for the delay I just looking into this issue

**Comment by Poseidon281** [comment]
> Hello 
> 
> Sorry for the delay I just looking into this issue 

Thanks other then this little bug it is a very good egg.


Answer: https://discord.com/channels/577993482761928734/1140025605740564581/1253724895292948540

**Comment by Luxxy-GF** [comment]
> > Hello
> > Sorry for the delay I just looking into this issue
> 
> Thanks other then this little bug it is a very good egg.
> 
> Answer: https://discord.com/channels/577993482761928734/1140025605740564581/1253724895292948540

what discord would this be coming from?

**Comment by Luxxy-GF** [comment]
okay should be know fixed thanks for speeding up the process for me should be
 just restart the container what will pull the latest docker image

**Comment by Luxxy-GF** [comment]
reopen this issue if you still having issues with this
